### ISSUE TITLE
Redundancy: Hide unimportant side panels

### ISSUE THREAD

**Issue by KrishSavani** [Pikel1997/3-Months-Of-Grind#2]
U can hide these:
![image](https://user-images.githubusercontent.com/74283604/163469228-a744c398-481f-4b3f-a5fd-06b5be163d76.png)
By going here:
![kunal](https://user-images.githubusercontent.com/74283604/163469534-3df36607-cdfd-40d7-a956-75f86e87d8bf.png)
![image](https://user-images.githubusercontent.com/74283604/163469583-536ab040-0dde-4e14-bdd3-d6196cf8dbeb.png)
Uncheck the things u don't want.

**Comment by Pikel1997** [comment]
Done, thanks for pointing it out.
